name: "Publish new release"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build_binary:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') # only merged release branches must trigger this
    name: Build binary
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Build ${{ matrix.os }} release binary
        id: build
        run: make build BUILD_ARGS='--release'

      - name: Extract version from branch name
        id: extract-version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "::set-output name=version::$VERSION"

      - name: Create archive
        id: create-archive
        run: |
          MACHINE=$(uname -m)
          KERNEL=$(uname -s)
          VERSION=${{ steps.extract-version.outputs.version }}

          ARCHIVE="cnd_${VERSION}_${KERNEL}_${MACHINE}.tar.gz"

          tar -C ./target/release --create --file=$ARCHIVE cnd

          echo "::set-output name=archive::$ARCHIVE"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-release-archive
          path: ${{ steps.create-archive.outputs.archive }}

  create_docker_image:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') # only merged release branches must trigger this
    name: Create and publish Docker image
    needs: build_binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Download ubuntu release package
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-latest-release-archive

      - name: Move binary into correct place for Docker build
        run: |
          mkdir -p ./target/release

          tar --extract -f ./ubuntu-latest-release-archive/*.tar.gz -C ./target/release/

      - name: Login to docker
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract version from branch name
        id: extract-version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "::set-output name=version::$VERSION"

      - name: Build docker image as ${{ steps.extract-version.outputs.version }} and latest
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"

          docker build . -t comitnetwork/cnd:$VERSION -t comitnetwork/cnd:latest

      - name: Test docker image by starting it and curling the cnd API
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          echo "::starting docker-container comitnetwork/cnd:$VERSION"
          docker run --publish 8000:8000 --detach --name cnd_container comitnetwork/cnd:$VERSION
          curl --fail localhost:9999/
          echo "::cnd API curled successfully"
          docker stop cnd_container
